from django.urls import path, include
from django.contrib.auth.views import LoginView
from django.views.generic import TemplateView
from . import views
from .views import (
    shiiregyosha_list, admin_home, edit_supplier, edit_supplier_confirm,
    capital_search, register_employee, supplier_listhe,
    change_password, admin_change_password, login_view, logout_view, doctor_home, uketuke_home, admin_dashboard,
    doctor_patient_search, doctor_medicine_instructions, medicine_confirmation, process_confirmed, treatment_history,
    treatment_history_detail
)
from .views import doctor_patient_search, receptionist_patient_search

urlpatterns = [
    path('', views.login_view, name='login'),
    path('logout_view/', views.logout_view, name='logout_view'),
    path('login_view/', views.login_view, name='login_view'),
    path('register/', views.register_employee, name='register_employee'),
    path('admin_home/', views.admin_home, name='admin_home'),
    path('doctor_home/', views.doctor_home, name='doctor_home'),
    path('uketuke_home/', views.uketuke_home, name='uketuke_home'),
    path('supplier_edit/', views.supplier_edit, name='supplier_edit'),
    path('patient_search/', views.patient_search, name='patient_search'),
    path('receptionist_home/', views.receptionist_home, name='receptionist_home'),
    path('change_employee_password/', views.change_employee_password, name='change_employee_password'),
    path('register_patient/', views.register_patient, name='register_patient'),
    path('change_patient_insurance/', views.change_patient_insurance, name='change_patient_insurance'),
    path('search_patient_by_name/', views.search_patient_by_name, name='search_patient_by_name'),
    path('shiiregyosha_list/', shiiregyosha_list, name='shiiregyosha_list'),
    path('supplier/', shiiregyosha_list, name='shiiregyosha_list'),
    path('supplier/<str:pk>/edit/', edit_supplier, name='supplier_edit'),
    path('supplier/<str:pk>/edit/confirm/', edit_supplier_confirm, name='supplier_edit_confirm'),
    path('supplier/capital_search/', capital_search, name='capital_search'),
    path('admin_home/register_employee/', register_employee, name='register_employee'),
    path('supplier_listhe/', supplier_listhe, name='supplier_listhe'),
    path('password_change/', change_password, name='change_password'),
    path('admin_password_change/<int:user_id>/', admin_change_password, name='admin_change_password'),
    path('accounts/login/', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('password_change_done/', TemplateView.as_view(template_name='kadai1/password_change_done.html'),
         name='password_change_done'),
    path('admin_password_change_done/', TemplateView.as_view(template_name='kadai1/admin_password_change_done.html'),
         name='admin_password_change_done'),
    path('', login_view, name='login'),
    path('password_change/', change_password, name='change_password'),
    path('admin_password_change/<int:user_id>/', admin_change_password, name='admin_change_password'),
    path('password_change_done/', TemplateView.as_view(template_name='kadai1/password_change_done.html'),
         name='password_change_done'),
    path('admin_password_change_done/', TemplateView.as_view(template_name='kadai1/admin_password_change_done.html'),
         name='admin_password_change_done'),
    path('admin_home/', admin_home, name='admin_home'),
    path('doctor_home/', doctor_home, name='doctor_home'),
    path('uketuke_home/', uketuke_home, name='uketuke_home'),
    path('admin_dashboard/', admin_dashboard, name='admin_dashboard'),
    path('doctor_patient_search/', doctor_patient_search, name='doctor_patient_search'),
    path('receptionist_patient_search/', receptionist_patient_search, name='receptionist_patient_search'),
    path('admin_home/', admin_home, name='admin_home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('doctor_medicine_instructions/<str:patient_id>/', doctor_medicine_instructions,
         name='doctor_medicine_instructions'),
    path('medicine_confirmation/', medicine_confirmation, name='medicine_confirmation'),
    path('process_confirmed/', process_confirmed, name='process_confirmed'),
    path('treatment_history/', treatment_history, name='treatment_history'),
    path('treatment_history_detail/<str:patient_id>/', treatment_history_detail, name='treatment_history_detail'),
    path('admin_home/', admin_home, name='admin_home'),
    path('accounts/', include('django.contrib.auth.urls')),
]