# Generated by Django 5.0.6 on 2024-06-24 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadai1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiiregyosha',
            name='shiiretel',
            field=models.CharField(max_length=15, verbose_name='仕入れ先電話番号'),
        ),
    ]
