# Generated by Django 5.0.6 on 2024-05-28 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadai1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='empid',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
