# Generated by Django 5.0.6 on 2024-06-07 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadai1', '0003_shiiregyosha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patid', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='患者 ID')),
                ('patfname', models.CharField(max_length=64, verbose_name='患者名')),
                ('patlname', models.CharField(max_length=64, verbose_name='患者姓')),
                ('hokenmei', models.CharField(max_length=64, verbose_name='保険証名記号番号')),
                ('hokenexp', models.DateField(verbose_name='有効期限')),
            ],
        ),
    ]
